---
title: "CASE STUDY TITLE"
author: "YOUR NAME"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r load_libraries, include=FALSE}
# Use this R-Chunk to load all your libraries!
#install.packages("tidyverse") # run this line once in console to get package
library(tidyverse)
library(buildings)
```

```{r load_data}
# Use this R-Chunk to import all your datasets!
buildings2 <- buildings0809%>%
  left_join(climate_zone_fips, by = c('FIPS.state', 'FIPS.county'))

build <- buildings2%>%
  filter(Type == 'Food_Beverage_Service')

not_restaurants <- c("development","Food preperation center", "Food Services center","bakery","Grocery","conceession","Cafeteria", "lunchroom","school","facility"," hall ")
standalone_retail <- c("Wine","Spirits","Liquor","Convenience","drugstore","Flying J", "Rite Aid ","walgreens ","Love's Travel ")
full_service_type <- c("Ristorante","mexican","pizza ","steakhouse"," grill ","buffet","tavern"," bar ","waffle","italian","steak house")
quick_service_type <- c("coffee"," java "," Donut ","Doughnut"," burger ","Ice Cream ","custard ","sandwich ","fast food "," bagel ")
quick_service_names <- restaurants$Restaurant[restaurants$Type %in% c("coffee","Ice Cream","Fast Food")]
full_service_names <- restaurants$Restaurant[restaurants$Type %in% c("Pizza","Casual Dining","Fast Casual")]

not_restaurants <- not_restaurants %>%
  str_c(collapse = '|')

standalone_retail <- standalone_retail %>%
  str_c(collapse = '|')

full_service_type <- full_service_type %>%
  str_c(collapse = '|')

quick_service_type <- quick_service_type %>%
  str_c(collapse = '|')

quick_service_names <- quick_service_names %>%
  str_c(collapse = '|')

full_service_names <- full_service_names %>%
  str_c(collapse = '|')

buildfood <- build %>%
  mutate(ProjectTitle = str_to_lower(ProjectTitle, locale = 'en')) %>%
  mutate(ProjectTitle = str_trim(ProjectTitle, side = 'both')) %>%
  mutate(subgroups = case_when(
    str_detect(ProjectTitle, str_c(not_restaurants, collapse = '|')) ~ 'Not a Restuarant', 
    str_detect(ProjectTitle, str_c(standalone_retail, collapse = '|')) ~ 'Standalone Retail',
    str_detect(ProjectTitle, str_c(full_service_type, collapse = '|')) ~ 'Full Service Restaurant',
    str_detect(ProjectTitle, str_c(full_service_names, collapse = '|')) ~ 'Full Service Restaurant',
    str_detect(ProjectTitle, str_c(quick_service_type, collapse = '|'))~ 'Quick Service Restaurant',
    str_detect(ProjectTitle, str_c(quick_service_names, collapse = '|'))~ 'Quick Service Restaurant',
    SqFt >= 4000 ~ 'Full Service Restaurant', 
    SqFt <4000 ~ 'Quick Service Restaurant'
  )) 

```

## Background



## Data Wrangling

```{r tidy_data}
# Use this R-Chunk to clean & wrangle your data!
buildfood%>%
  ggplot()+
  geom_bar(mapping = aes(fill = subgroups, x = Year), stat = 'count')
```

## Data Visualization

```{r plot_data}
# Use this R-Chunk to plot & visualize your data!

```

## Conclusions
