---
title: "CASE STUDY TITLE"
author: "YOUR NAME"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:  
    keep_md: true
    toc: true
    toc_float: true
    code_folding: hide
    fig_height: 6
    fig_width: 12
    fig_align: 'center'
---

```{r load_libraries, include=FALSE}

library(tidyverse)
library(datasets)
library(pander)
library(cluster)
```

### Agglomerative Hierarchical Clustering

```{r load_data}
mydata <-  state.x77

distance <-  dist(as.matrix(mydata))#Normal clustering with original data
hc <-  hclust(distance)
plot(hc)

data_scaled <-  scale(mydata) #scaled data clustering
distance2 <-  dist(as.matrix(data_scaled))
hc1 <- hclust(distance2)
plot(hc1)

noarea <- as.matrix(as.data.frame(data_scaled) %>% #taking out area
  select(1:7))

distance3 <- dist(as.matrix(noarea))
hc2 <- hclust(distance3)
plot(hc2)

#Clustering only on Frost attribute
onlyfrost <- as.data.frame(data_scaled) %>%
  select(7)

distance4 <- dist(as.matrix(onlyfrost))
hc3 <- hclust(distance4)
plot(hc3)

```

### K-Means Clustering
```{r}
kdata <- data_scaled
myClusters <- kmeans(kdata, 3)
pander(summary(kdata))
myClusters$centers
myClusters$cluster
myClusters$withinss
myClusters$tot.withinss
clusplot(kdata, myClusters$cluster, color=TRUE, shade=TRUE, labels=2, lines=0)

```

## For loop to find best K
```{r}
total_ss <- c()

for (i in 1:25) {
  myClusters <- kmeans(kdata, i)
  total_ss[[i]] <- myClusters$tot.withinss
}

plot(total_ss, xlab = 'K-value')
```

## Recluserting with K = 4
```{r}
myClusters <- kmeans(kdata, 5)
pander(summary(kdata))
myClusters$centers
myClusters$cluster
myClusters$withinss
myClusters$tot.withinss
clusplot(kdata, myClusters$cluster, color=TRUE, shade=TRUE, labels=2, lines=0)
clusterdata <- as.data.frame(myClusters$cluster) 
clusters <- cbind(State = rownames(clusterdata), clusterdata)
rownames(clusters) <- 1:nrow(clusters)
pander(clusters%>%
  arrange(`myClusters$cluster`))

clusplot(kdata, myClusters$cluster, color=TRUE, shade=TRUE, labels=2, lines=0)
```








